# genome-scale metabolic model of the universe (pan-genome) model
pan_gem_model_file: "CDC317/Cparapsilosis.xml"

# this file contains two columns: ReferenceRxnID and QueryRxnID (reaction IDs)
pan_gem_gene_id_mapping_file: "CDC317/GeneID_mapping.csv"

# protein fasta file of the pan-genome model
pan_gem_protein_sequence_file: "CDC317/protein.faa"

# protein fasta files of the query genomes (one fasta file per query genome)
query_protein_sequence_files: "MSK_protein_faa/"

# data output directory (each query genome has its own subfolder under this directory)
output_folder: "Output"

# cutoff value used to determine whether a protein in the query genome is present in the pan-genome model
protein_identity_score_cutoff: 95

# available gap filling algorithms include
# "minrxnnum": minimum number of reactions
# "maxavescore": maximum average score
# "mcs": minimal cut set
gapfilling_method: "mcs"

# number of cpus
n_cpus: 28
